import manifest from '../data/graphicalAbstracts.json'

/*
  Graphical abstracts are served as three variants generated by
  scripts/optimize_images.js — AVIF and WebP at 1600px for the inline
  render, plus a full-resolution WebP behind the click-through.

  The inline image displays at roughly 752 CSS px (max-h-[420px] on a 16:9
  diagram), so 1600px covers a 2x device pixel ratio. The click-through
  keeps the native 2752x1536 detail and stays WebP because a bare <a href>
  gets no content negotiation — it needs the format with wider support.
*/

const BASE = '/graphical-abstracts'

/** Full-resolution URL for the click-through link. */
export const fullSizeUrl = (slug) => `${BASE}/${slug}-full.webp`

/** Intrinsic size of the inline variant, or null for an unknown slug. */
export const inlineDimensions = (slug) => manifest[slug] || null

export default function GraphicalAbstract({ slug, title, className = '' }) {
  const dims = inlineDimensions(slug)

  /* An unknown slug means the data and the generated files have drifted
     apart. Render nothing rather than a broken image. */
  if (!dims) return null

  return (
    <a
      href={fullSizeUrl(slug)}
      target="_blank"
      rel="noopener noreferrer"
      title="Click to open the full-resolution graphical abstract in a new tab"
    >
      {/* display:contents keeps <picture> out of the layout tree, so the
          img sizes against the real container exactly as a bare <img> did */}
      <picture className="contents">
        <source srcSet={`${BASE}/${slug}-1600.avif`} type="image/avif" />
        <source srcSet={`${BASE}/${slug}-1600.webp`} type="image/webp" />
        {/*
          width/height carry the intrinsic aspect ratio so the browser
          reserves the correct box before the bytes arrive — without them
          the expanding post jumps as each image loads.
        */}
        <img
          src={`${BASE}/${slug}-1600.webp`}
          alt={`Graphical abstract for ${title}`}
          width={dims.width}
          height={dims.height}
          loading="lazy"
          decoding="async"
          className={className}
        />
      </picture>
    </a>
  )
}
